### ISSUE TITLE
Can't find file

### ISSUE THREAD

**Issue by Zt-freak** [jbostoen/ZTStudio#34]
I am trying to open a file which exists, however the program can't find the file.
![image](https://user-images.githubusercontent.com/26248881/124657908-60342e00-dea3-11eb-9587-bd1e22d0b6fd.png)

**Comment by jbostoen** [comment]
Is the .pal file actually the file you're trying to open?
Or are you trying to open a graphic?

**Comment by Zt-freak** [comment]
If I try to open a .pal file I get a different response
![image](https://user-images.githubusercontent.com/26248881/124760475-13973400-df31-11eb-9dd3-bb156415a0fb.png)

**Comment by jbostoen** [comment]
So originally you tried to open a ZT1 Graphics file.
What was the path of that file?

**Comment by Zt-freak** [comment]
C:\Users\bnkho\Downloads\Purple Haze Path\PurpleHazePath\paths\lurppath\idle\1

**Comment by jbostoen** [comment]
It might actually be because the filename is too long.
Try a shorter path (put your files under c:\ztfiles\PurpleHazePath or sth)

**Comment by HENDRIX-ZT2** [comment]
Or due to the spaces in the path.

**Comment by Zt-freak** [comment]
ah yes, It's the spaces.

Can I turn this into a feature suggestion? spaces in path support.

**Comment by jbostoen** [comment]
Has the "root folder" been set correctly?
The last part (paths/lurppath/idle/1) must be spaceless.
But as for the root folder, it should indeed support spaces.

**Comment by Zt-freak** [comment]
the last part was spaceless. `C:\Users\bnkho\Downloads\Purple Haze Path\PurpleHazePath\paths\lurppath\idle\1` was the path

**Comment by jbostoen** [comment]
And the root folder is set to "C:\Users\bnkho\Downloads\Purple Haze Path\PurpleHazePath\" ?

**Comment by Zt-freak** [comment]
yes
