### ISSUE TITLE
Trouble with finding the right path

### ISSUE THREAD

**Issue by Zt-freak** [jbostoen/ZTStudio#35]
This is from animals.ztd and ZTStudio can't seem to find the right path, it duplicates part of the path.
![image](https://user-images.githubusercontent.com/26248881/155413842-45def823-ae2e-452a-89f3-62acd3b056a1.png)

**Comment by Zt-freak** [comment]
Apparently, it does work when I put it in another folder and open that newly created parent folder.

**Comment by TheRisingApe** [comment]
yup make it easy on yourself and make sure that the folder you extract from the game files goes in to a newly created folder that you can then use as your root folder.
